// Autogenerated by measurement-kit/ffi tools; DO NOT EDIT!

package org.openobservatory.measurement_kit.nettest;

class NettestWrapper extends org.openobservatory.measurement_kit.nettest.swig.Nettest {
  NettestWrapper(Nettest parent, org.openobservatory.measurement_kit.nettest.swig.Settings settings) {
    super(settings);
    parent_ = parent;
  }

  public void on_failure_asn_lookup(org.openobservatory.measurement_kit.nettest.swig.FailureASNLookupEvent swigEvent) {
    FailureASNLookupEvent event = new FailureASNLookupEvent();
    event.failure = swigEvent.getFailure();
    parent_.on_failure_asn_lookup(event);
  }

  public void on_status_update_performance(org.openobservatory.measurement_kit.nettest.swig.StatusUpdatePerformanceEvent swigEvent) {
    StatusUpdatePerformanceEvent event = new StatusUpdatePerformanceEvent();
    event.direction = swigEvent.getDirection();
    event.elapsed = swigEvent.getElapsed();
    event.num_streams = swigEvent.getNum_streams();
    event.speed_kbps = swigEvent.getSpeed_kbps();
    parent_.on_status_update_performance(event);
  }

  private Nettest parent_;
}
