// Autogenerated by measurement-kit/ffi tools; DO NOT EDIT!

package org.openobservatory.measurement_kit.nettest;

public class Options {
  public String bouncer_base_url = "";
  public String dns_name_server = "";
  public boolean ignore_bouncer_error = true;
  public double max_runtime = -1.0;
  // <function name_to_mkname at 0x10b79f7d0> name_to_mkname
}
