// Autogenerated by measurement-kit/ffi tools; DO NOT EDIT!

package org.openobservatory.measurement_kit.nettest;

public class Settings {
  public java.util.Map<String, String> annotations = new java.util.HashMap<String, String>();
  public java.util.Vector<String> disabled_events = new java.util.Vector<String>();
  public String name = "";
  public Options options = new Options();
}
