/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Libndt_WRAP_H_
#define SWIG_Libndt_WRAP_H_

class SwigDirector_Nettest : public mk::cxx11::Nettest, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_Nettest(JNIEnv *jenv);
    SwigDirector_Nettest(JNIEnv *jenv, mk::cxx11::Settings s);
    virtual void on_failure_asn_lookup(mk::cxx11::FailureASNLookupEvent const &arg0);
    virtual void on_status_update_performance(mk::cxx11::StatusUpdatePerformanceEvent const &arg0);
    virtual ~SwigDirector_Nettest();
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};


#endif
