/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openobservatory.measurement_kit.nettest.swig;

public class EventDeleter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventDeleter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventDeleter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibndtJNI.delete_EventDeleter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EventDeleter() {
    this(LibndtJNI.new_EventDeleter(), true);
  }

}
