/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openobservatory.measurement_kit.nettest.swig;

public class FailureASNLookupEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FailureASNLookupEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FailureASNLookupEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibndtJNI.delete_FailureASNLookupEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFailure(String value) {
    LibndtJNI.FailureASNLookupEvent_failure_set(swigCPtr, this, value);
  }

  public String getFailure() {
    return LibndtJNI.FailureASNLookupEvent_failure_get(swigCPtr, this);
  }

  public FailureASNLookupEvent() {
    this(LibndtJNI.new_FailureASNLookupEvent(), true);
  }

}
