/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openobservatory.measurement_kit.nettest.swig;

public class Nettest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Nettest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Nettest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibndtJNI.delete_Nettest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    LibndtJNI.Nettest_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    LibndtJNI.Nettest_change_ownership(this, swigCPtr, true);
  }

  public void on_failure_asn_lookup(FailureASNLookupEvent arg0) {
    if (getClass() == Nettest.class) LibndtJNI.Nettest_on_failure_asn_lookup(swigCPtr, this, FailureASNLookupEvent.getCPtr(arg0), arg0); else LibndtJNI.Nettest_on_failure_asn_lookupSwigExplicitNettest(swigCPtr, this, FailureASNLookupEvent.getCPtr(arg0), arg0);
  }

  public void on_status_update_performance(StatusUpdatePerformanceEvent arg0) {
    if (getClass() == Nettest.class) LibndtJNI.Nettest_on_status_update_performance(swigCPtr, this, StatusUpdatePerformanceEvent.getCPtr(arg0), arg0); else LibndtJNI.Nettest_on_status_update_performanceSwigExplicitNettest(swigCPtr, this, StatusUpdatePerformanceEvent.getCPtr(arg0), arg0);
  }

  public Nettest() {
    this(LibndtJNI.new_Nettest__SWIG_0(), true);
    LibndtJNI.Nettest_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Nettest(Settings s) {
    this(LibndtJNI.new_Nettest__SWIG_1(Settings.getCPtr(s), s), true);
    LibndtJNI.Nettest_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void run() {
    LibndtJNI.Nettest_run(swigCPtr, this);
  }

}
