/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openobservatory.measurement_kit.nettest.swig;

public class VectorString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibndtJNI.delete_VectorString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorString() {
    this(LibndtJNI.new_VectorString__SWIG_0(), true);
  }

  public VectorString(long n) {
    this(LibndtJNI.new_VectorString__SWIG_1(n), true);
  }

  public long size() {
    return LibndtJNI.VectorString_size(swigCPtr, this);
  }

  public long capacity() {
    return LibndtJNI.VectorString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    LibndtJNI.VectorString_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return LibndtJNI.VectorString_isEmpty(swigCPtr, this);
  }

  public void clear() {
    LibndtJNI.VectorString_clear(swigCPtr, this);
  }

  public void add(String x) {
    LibndtJNI.VectorString_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return LibndtJNI.VectorString_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    LibndtJNI.VectorString_set(swigCPtr, this, i, val);
  }

}
