/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class FailureReportCreate {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FailureReportCreate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FailureReportCreate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MkNettestJNI.delete_FailureReportCreate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFailure(String value) {
    MkNettestJNI.FailureReportCreate_failure_set(swigCPtr, this, value);
  }

  public String getFailure() {
    return MkNettestJNI.FailureReportCreate_failure_get(swigCPtr, this);
  }

  public FailureReportCreate() {
    this(MkNettestJNI.new_FailureReportCreate(), true);
  }

  public final static String key = MkNettestJNI.FailureReportCreate_key_get();
}
