/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class Log {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Log(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Log obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MkNettestJNI.delete_Log(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLog_level(String value) {
    MkNettestJNI.Log_log_level_set(swigCPtr, this, value);
  }

  public String getLog_level() {
    return MkNettestJNI.Log_log_level_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    MkNettestJNI.Log_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return MkNettestJNI.Log_message_get(swigCPtr, this);
  }

  public Log() {
    this(MkNettestJNI.new_Log(), true);
  }

  public final static String key = MkNettestJNI.Log_key_get();
}
