/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusMeasurementDone {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusMeasurementDone(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusMeasurementDone obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MkNettestJNI.delete_StatusMeasurementDone(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdx(long value) {
    MkNettestJNI.StatusMeasurementDone_idx_set(swigCPtr, this, value);
  }

  public long getIdx() {
    return MkNettestJNI.StatusMeasurementDone_idx_get(swigCPtr, this);
  }

  public StatusMeasurementDone() {
    this(MkNettestJNI.new_StatusMeasurementDone(), true);
  }

  public final static String key = MkNettestJNI.StatusMeasurementDone_key_get();
}
