/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusGeoipLookup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusGeoipLookup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusGeoipLookup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MkNettestJNI.delete_StatusGeoipLookup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProbe_ip(String value) {
    MkNettestJNI.StatusGeoipLookup_probe_ip_set(swigCPtr, this, value);
  }

  public String getProbe_ip() {
    return MkNettestJNI.StatusGeoipLookup_probe_ip_get(swigCPtr, this);
  }

  public void setProbe_asn(String value) {
    MkNettestJNI.StatusGeoipLookup_probe_asn_set(swigCPtr, this, value);
  }

  public String getProbe_asn() {
    return MkNettestJNI.StatusGeoipLookup_probe_asn_get(swigCPtr, this);
  }

  public void setProbe_cc(String value) {
    MkNettestJNI.StatusGeoipLookup_probe_cc_set(swigCPtr, this, value);
  }

  public String getProbe_cc() {
    return MkNettestJNI.StatusGeoipLookup_probe_cc_get(swigCPtr, this);
  }

  public void setProbe_network_name(String value) {
    MkNettestJNI.StatusGeoipLookup_probe_network_name_set(swigCPtr, this, value);
  }

  public String getProbe_network_name() {
    return MkNettestJNI.StatusGeoipLookup_probe_network_name_get(swigCPtr, this);
  }

  public StatusGeoipLookup() {
    this(MkNettestJNI.new_StatusGeoipLookup(), true);
  }

  public final static String key = MkNettestJNI.StatusGeoipLookup_key_get();
}
