/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusUpdateWebsites {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusUpdateWebsites(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusUpdateWebsites obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MkNettestJNI.delete_StatusUpdateWebsites(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUrl(String value) {
    MkNettestJNI.StatusUpdateWebsites_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return MkNettestJNI.StatusUpdateWebsites_url_get(swigCPtr, this);
  }

  public void setStatus(String value) {
    MkNettestJNI.StatusUpdateWebsites_status_set(swigCPtr, this, value);
  }

  public String getStatus() {
    return MkNettestJNI.StatusUpdateWebsites_status_get(swigCPtr, this);
  }

  public StatusUpdateWebsites() {
    this(MkNettestJNI.new_StatusUpdateWebsites(), true);
  }

  public final static String key = MkNettestJNI.StatusUpdateWebsites_key_get();
}
