// Part of Measurement Kit <https://measurement-kit.github.io/>.
// Measurement Kit is free software under the BSD license. See AUTHORS
// and LICENSE for more information on the copying conditions.

/*-
 *  __      __  _____ __________  _______  .___ _______    ________
 * /  \    /  \/  _  \\______   \ \      \ |   |\      \  /  _____/
 * \   \/\/   /  /_\  \|       _/ /   |   \|   |/   |   \/   \  ___
 *  \        /    |    \    |   \/    |    \   /    |    \    \_\  \
 *   \__/\  /\____|__  /____|_  /\____|__  /___\____|__  /\______  /
 *        \/         \/       \/         \/            \/        \/
 *
 * Autogenerated by measurement-kit/ffi-tools; DO NOT EDIT!
 *
 * See https://github.com/measurement-kit/ffi-tools for more information.
 */

package io.ooni.mk.nettest.settings;

public class Common {
  public static final String err = "ERR";
  public static final String warning = "WARNING";
  public static final String info = "INFO";
  public static final String debug = "DEBUG";
  public static final String debug2 = "DEBUG2";
  public java.util.Map<String, String> annotations = new java.util.HashMap<String, String>();
  public java.util.Vector<String> disabledEvents = new java.util.Vector<String>();
  public java.util.Vector<String> inputs = new java.util.Vector<String>();
  public java.util.Vector<String> inputFilepaths = new java.util.Vector<String>();
  public String logFilepath = "";
  public String logLevel = "ERR";
  public String outputFilepath = "";
  public String bouncerBaseUrl = "https://bouncer.ooni.io";
  public String collectorBaseUrl = "";
  public String dnsNameserver = "";
  public String dnsEngine = "system";
  public String geoipAsnPath = "";
  public String geoipCountryPath = "";
  public boolean ignoreBouncerError = true;
  public boolean ignoreOpenReportError = true;
  public double maxRuntime = -1.0;
  public String netCaBundlePath = "";
  public double netTimeout = 10.0;
  public boolean noBouncer = false;
  public boolean noCollector = false;
  public boolean noAsnLookup = false;
  public boolean noCcLookup = false;
  public boolean noIpLookup = false;
  public boolean noFileReport = false;
  public boolean noResolverLookup = false;
  public String probeAsn = "";
  public String probeCc = "";
  public String probeIp = "";
  public boolean randomizeInput = true;
  public boolean saveRealProbeAsn = true;
  public boolean saveRealProbeCc = true;
  public boolean saveRealProbeIp = false;
  public boolean saveRealResolverIp = true;
  public String softwareName = "measurement_kit";
  public String softwareVersion = "";
}


