#!/bin/sh
set -e

python src/main/spec/nettest.py src/main/template/nettest/nettest.hpp.j2 \
    | clang-format - > include/measurement_kit/nettest/nettest.hpp

(
  swig -Iinclude -c++ -java -package io.ooni.mk.nettest.swig \
    src/main/cpp/libmeasurementkit-jni/bindings.swigcxx

  install -d src/main/java/io/ooni/mk/nettest/swig

  mv src/main/cpp/libmeasurementkit-jni/*.java \
    src/main/java/io/ooni/mk/nettest/swig
)

python src/main/spec/nettest.py src/main/template/nettest/nettest.java.j2 \
    | ./script/cutter

python src/main/spec/nettest.py src/main/template/ffi/nettest.hpp.j2 \
    | clang-format - > include/measurement_kit/ffi/nettest.hpp

python src/main/spec/nettest.py src/main/template/ffi/README.md.j2 \
    > include/measurement_kit/ffi/README.md
